version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./models/saved_models:/app/models/saved_models
      - ./data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-botuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-botpass}
      POSTGRES_DB: ${DB_NAME:-botdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
