version: '3.8'
services:
  legal_bot:
    build: .
    container_name: legal_assistant
    env_file:
      - .env
    command: python app_mistral_minimal.py
    restart: unless-stopped
volumes:
  data:
